config/routes.rb
Rails.application.routes.draw do
  resources :quotes, only: [:index, :new, :create]
  resource :random_combination, only: [:show]

  root 'quotes#index'

  resource :sampled_types, only: [:show]
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user

  def sentences
    text.split('.').map(&:strip)
  end

  def user_ip_address
    user.latest_ip_address
  end
end

app/models/random_combiner.rb
class RandomCombiner
  def combine_two_quotes(quotes)
    sentences = quotes.flat_map(&:sentences)

    sentence1, sentence2 = random_sentence_pair(sentences)

    split_word = random_split_word(sentence1, sentence2)
    left = sentence1.split(split_word)[0]
    right = sentence2.split(split_word)[1]

    "#{left} #{split_word} #{right}."
  end

  private

  def random_split_word(sentence1, sentence2)
    common_words = sentence1.split & sentence2.split
    common_words[rand(common_words.size)] + ' '
  end

  def random_sentence_pair(sentences)
    index1 = rand(sentences.size)
    index2 = rand_not_equal(sentences.size, index1)
    [sentences[index1], sentences[index2]]
  end

  def rand_not_equal(size, cannot_equal)
    loop do
      index = rand(size)
      return index if index != cannot_equal
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_or_create_by(latest_ip_address: request.env['REMOTE_ADDR'])
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end

  def create
    Quote.create!(quote_params)
    redirect_to quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:text, :author, :year)
          .merge(user: current_user)
  end
end

app/controllers/random_combinations_controller.rb
class RandomCombinationsController < ApplicationController
  def show
    @text = RandomCombiner.new.combine_two_quotes(cached_quotes)
  end

  private

  def cached_quotes
    Rails.cache.fetch('quotes', expires_in: 30.seconds) do
      Quote.all.to_a
    end
  end
end

app/controllers/sampled_types_controller.rb
class SampledTypesController < ApplicationController
  def show
    render json: JSON.pretty_generate(TypeTracer::TypeSampler.sampled_type_info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/random_combination_helper.rb
module RandomCombinationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Random Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container theme-showcase" role="main">
  <div class="jumbotron"><h2>Quote Randomizer</h2></div>

  <%= yield %>
</div>

</body>
</html>

app/views/quotes/index.html.erb
<p>
  <%= link_to 'New Quote', new_quote_path, class: 'btn btn-lg btn-primary' %>
  <%= link_to 'Random Combination', random_combination_path, class: 'btn btn-lg btn-default' %>
</p>
<div class="page-header">
  <h3>Quotes</h3>
</div>

<% @quotes.each do |quote| %>
  <blockquote>
    <p><%= quote.text %></p>
    <footer><%= quote.author %></footer>
  </blockquote>
<% end %>

app/views/quotes/new.html.erb
<%= form_for(@quote) do |f| %>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, rows: 4, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', quotes_path, class: 'btn btn-default btn-lg' %>
  </div>
<% end %>

app/views/random_combinations/show.html.erb
<blockquote>
  <p><%= @text %></p>
  <footer>Famous people and a random number generator</footer>
</blockquote>

<%= link_to 'Another Combination', random_combination_path, class: 'btn btn-primary btn-lg' %>
<%= link_to 'Back to Quotes', quotes_path, class: 'btn btn-default btn-lg' %>